### PR TITLE
Added --geojson flag for geojson output.

### PR DESCRIPTION
**Pull request by wiseman**
E.g. `dji-log-parser log.txt --geojson path.geojson --output records.json`. Converts the geographic coordinates in the OSD records to a GeoJSON LineString, and outputs a geojson file.

### CODE REVIEW

**Comment by lvauvillier** [comment]
Looks great! Merged. Thanks a lot, @wiseman! Perhaps in a future version, we could consider adding an option for the sampling rate. The high definition sometimes makes certain paths appear shaky.

**Comment by wiseman** [comment]
I was thinking the same thing after seeing some paths that consist of thousands of points but actually only cover a few centimeters. I've experimented with the Ramer-Douglas-Peucker algorithm on log paths and it worked well. Maybe I'll add that today.

**Comment by lvauvillier** [comment]
Oh, it will be great!

**Comment by MAVProxyUser** [comment]
@wiseman did you also have a patch that adds GPS Lat / Lon to the extracted images as an EXIF header?

**Comment by MAVProxyUser** [comment]
ope, never mind. Looks like that was *just* added yesterday: https://github.com/lvauvillier/dji-log-parser/commit/9b54ba821e39e9bd3d0bab65267517c99a354f4c

**Pull request merged**
